name: 'Update Branch'
description: 'Merge your pull request in order when enabled the `Require branches to be up to date before merging`'
author: 'lcdsmao'
branding:
  icon: 'zap'
  color: 'yellow'
inputs:
  token:
    required: true
    description: 'Require personal access token to access branch protection rules or trigger other workflows.'
  autoMergeMethod:
    required: false
    description: 'Method to use when enable pull request auto merge.'
    default: 'MERGE'
  requiredLabels:
    required: false
    description: 'Labels need to be present for a pull request.'
  protectedBranchNamePattern:
    required: false
    description: 'The name pattern of the base branch that your pull request wants to merge into. Branch protection rule with the same name pattern must be existed. If not set, the default behavior is to find the name pattern of main or master.'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
