name: 'update-branch'
description: 'Merge your pull request in order when enabled the `Require branches to be up to date before merging`'
icon: 'git-pull-request'
color: 'orange'
author: 'lcdsmao'
inputs:
  token:
    required: true
    description: 'Github Token'
  recordIssueNumber:
    required: true
    description: 'Record working progress'
  approvedCount:
    required: true
    description: 'At least the approved count of the branch to update'
    default: '0'
  statusChecks:
    required: true
    description: 'Multiple status checks required to be success'
runs:
  using: 'node12'
  main: 'dist/index.js'
