name: 'update-branch'
description: 'Update Branch'
author: 'ca-love'
inputs:
  token:
    required: true
    description: 'Github Token'
  approvedCount:
    required: true
    description: 'At least the approved count of the branch to update'
    default: '0'
  recordIssueNumber:
    required: true
    description: 'Record working progress'
runs:
  using: 'node12'
  main: 'dist/index.js'
